src/bl.js

BL Coding. Remove encoding of fileId

---

src/security-url-builder.js

- BKNDLSS-14178 fix on reset "Add/Set Relation" permissions

feat: (Security) DataPermissions

---

src/geo.js

- BKNDLSS-14433 fix load geo relations

feat: (Data) GeoRelations

---

src/bl.js

Set of methods for working with Codeless Bl Services

BL Codeless Services

---

package.json
src/tables.js

- upgrade backendless-request to version 0.0.5
- add an ability to resetCache before load TableRecordsCount

feat: (Data) RecordsCount

---

src/project-template.js
src/urls.js

... and make files console section url

Use console route for project template icon

---

src/codeless.js
src/index.js
src/urls.js

- add BKNDLSS-14584 Support for "Function Library"

feat: (Codeless) FunctionLibrary

---

src/codeless.js
src/urls.js

- add an route to get definition of ApiServices Blocks

feat: (Codeless) ApiServices

---

src/bl.js

- add method for update Codeless Service Methods

feat: (BL) API Service Methods

---

src/codeless.js
src/urls.js

- add method for deploy codeless model

feat: (Codeless) Deploy Model

---

src/codegen.js

Fix codegen icons

---

src/apps.js

The method works with changes added according to the internal ticket BKNDLSS-18595

Apps: add method to rename app

---

src/analytics.js
src/dev-permissions.js
src/settings.js

- add api methods for Custom Api Keys
- adapt query for retrieving Analytics
- replace Dev Permission REGENERATE_API_KEYS by MANAGE_API_KEYS

feat: Custom Api Keys

---

src/dev-team.js

Reverts Backendless/Console-SDK#77

Revert "feat added transferOwnership route"

---

src/settings.js

Route created for console's App-to-app deployment task to change value of built-in api-keys

added route to change built-in api key's value

---

src/dev-permissions.js

added permission to promote from one app to another

---

src/security.js

fix bug with permissions mapping when business logic service with 0 methods returns user permissions = null

fixed mapping bug when bl user-permissiong get request returns null

---

src/index.js

Added destroy() method to reject already started promises

added destroy request method

---

src/apps.js

BKNDLSS-23069 - Add Get App Cloning status method in Console-SDK

BKNDLSS-23069 - Add Get App Cloning status method in Console-SDK

---

src/dev-permissions.js
src/settings.js

BKNDLSS-23453 -  Remove git support on console

BKNDLSS-23453 -  Remove git support on console

---

src/data-views.js
src/urls.js
src/utils/cache-tags.js
src/utils/views.js

* BKNDLSS-23563 – View data grouping

BKNDLSS-23563 – View data grouping (#137)

---

src/utils/views.js

BKNDLSS-24077 – Console. Add ability to provide group depth during group find request

BKNDLSS-24077 – Console. Add ability to provide group depth during group find request

---

src/security.js

https://bugs.backendless.com/browse/BKNDLSS-23951

BKNDLSS-23951 Add paging to the User Permissions modal

---

src/users.js

Change provider callback url

---

src/dev-permissions.js

Fix columns visibility permissions

Fix columns visibility permissions

---

src/tables.js

Load relations count request. Remove "property" from query

Load relations count request. Remove "property" from query

---

src/counters.js
src/urls.js

Added the ability to get all counters

Added the ability to get all counters

---

src/files.js
src/urls.js
src/utils/path.js

Fixed problem with filesystem when users couldn't delete/rename/move/etc. files that contain plus in name.

Fix URL encoding for working with a file system.

---

src/visualizations.js

Visualizations

---

src/utils/table.js

Increase support for query properties

Increase support for query properties

---

src/visualizations.js

Add load published containers action

Add load published containers action

---

src/user.js

BKNDLSS-31966 Adapt "invited developer registration" page to support invitations for workspaces

---

src/automation.js

BKNDLSS-34752 - Codeless. Support new automations API

BKNDLSS-34752 - Codeless. Support new automations API

---

src/automation.js

AUTO-68 - Change route to retrieve flow triggers

AUTO-68 - Change route to retrieve flow triggers

---

src/automation.js

AUTO-310 - Flow-wide SLA support, AUTO-331 - SLA Calendar support

AUTO-310 - Flow-wide SLA support, AUTO-331 - SLA Calendar support

---

src/data-to-visualize.js

Add method for update all existed dashboards

[DASH-363] Apply layout type for all dashboards

---

src/automation.js

AUTO-394 - Flow SLA support. Server side

AUTO-394 - Flow SLA support. Server side

---

src/automation.js

AUTO-501 - Real-Time Logging UI

AUTO-501 - Real-Time Logging UI

---

src/tables.js

DATA-92  - [SUPPORT] Delete request with special characters does not work

DATA-92 - [SUPPORT] Delete request with special characters does not work

---

src/automation.js

FR-338 - Error When Editing Timer in Flow List

FR-338 - Error When Editing Timer in Flow List

---

src/automation.js

FR-844 - Real-Time Logging UI

---

src/fr-extensions.js

FR-1262 - Normalize retrieving FR Shared Extensions elements from NodeAPI Server

---

package-lock.json
package.json
src/bl.js

CS-39 - Error for handlers for tables with special characters

---

src/bl.js

MAR-48  - Problems with twillio in applications where it was already installed

---

src/automation.js

FR-1483 - Server. Learning Mode Improvements

FR-1483 - Server. Learning Mode Improvements

---

src/automation.js
src/gamification.js

Reverts Backendless/Console-SDK#457

Revert "Flowrunner achievements"

---

src/automation.js

FR-1520 - Support for SubFlows

FR-1520 - Support for SubFlows
